### ISSUE TITLE
about rviz

### ISSUE THREAD

**Issue by tcjcxy30** [jnez71/lqRRT#12]
Hi Jason Nezvadovitz:
    Thankyou for you project.
    I want to know how to set in rviz so that  i can see the GUI like the picture you paste in "Readme"?
    I copy the lqrrt.rviz into .rviz fold and there is a "global status:warn -- no tf data" at rviz panel

**Comment by jnez71** [comment]
@CxyCH 
Hmm. So with lqrrt.rviz in your .rviz folder, you should be able to open rviz and then click File -> Open Config and then select lqrrt.rviz from the .rviz folder. This should create the default view for my ROS demo. Then after running catkin_make on the lqrrt_ros package, do
`roslaunch lqrrt_ros lqrrt_sim.launch`
and 2 new windows should appear: a command GUI and a drawing pane for drawing obstacles. For the command GUI, set move_type to 'drive' and then send various goals (and for fun, increase the last option 'speed_factor' to something greater than 1). For the drawing pane, left-click to draw obstacles, right-click to erase, press q to clear all, and esc to exit. Here is a video so you can follow these steps:
https://www.youtube.com/watch?v=XIyVz5p564E
You might notice that it says "behavior: car" and such. This is a simulation for a boat, actually. "car behavior" refers to the fact that I make it more likely for the boat to move tangent to its path like a car would, even though physically it can still turn in place.
