### ISSUE TITLE
CV2 Error

### ISSUE THREAD

**Issue by mattlangford** [jnez71/lqRRT#5]
This (extremely rare and seemingly random) error occurs during normal running:

``` bash
Preparing: drive
Rotating towards goal (duration: 0.96)
OpenCV Error: Bad flag (parameter or structure field) (Unrecognized or unsupported array type) in cvGetMat, file /home/matt/Downloads/opencv-2.4.9/modules/core/src/array.cpp, line 2482
[ERROR] [WallTime: 1477538455.157950] Exception in your execute callback: /home/matt/Downloads/opencv-2.4.9/modules/core/src/array.cpp:2482: error: (-206) Unrecognized or unsupported array type in function cvGetMat

Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 291, in executeLoop
    self.execute_callback(goal)
  File "/home/matt/mil_ws/src/lqRRT/demos/lqrrt_ros/nodes/lqrrt_node.py", line 255, in move_cb
    clean_update = self.tree_chain()
  File "/home/matt/mil_ws/src/lqRRT/demos/lqrrt_ros/nodes/lqrrt_node.py", line 310, in tree_chain
    self.goal_bias, self.sample_space, self.guide = self.select_exploration()
  File "/home/matt/mil_ws/src/lqRRT/demos/lqrrt_ros/nodes/lqrrt_node.py", line 540, in select_exploration
    area, rect = cv2.floodFill(test_flood, np.zeros((test_flood.shape[0]+2, test_flood.shape[1]+2), np.uint8), ss_goal, 69)
error: /home/matt/Downloads/opencv-2.4.9/modules/core/src/array.cpp:2482: error: (-206) Unrecognized or unsupported array type in function cvGetMat
```

**Comment by jnez71** [comment]
My current hypothesis is that one of the dimensions of ss_img is going to zero length, but based on the way things were when this happened, I'm not sure why that'd be the case. I am going to surround that block with a try-except so we can get a look at ss_img (and every argument of that floodFill) if this ever happens again.

``` python
test_flood = np.copy(ss_img)
try:
    area, rect = cv2.floodFill(test_flood, np.zeros((test_flood.shape[0]+2, test_flood.shape[1]+2), np.uint8), ss_goal, 69)
    if test_flood[ss_seed[1], ss_seed[0]] == 69:
        gs[:2] = (np.add([col, row], [last_offsets[0], last_offsets[1]]).astype(np.float64) / self.ogrid_cpm) + self.ogrid_origin
        found_entry = True
        break
except:
    print("\nA sample space image during select_exploration may have become degenerate. How odd.")
    print("type(ss_img): {}".format(type(ss_img)))
    print("np.shape(ss_img): {}".format(np.shape(ss_img)))
    print("current push: {}".format(push))
    print("ss_goal: {}".format(ss_goal))
    print("\nTerminating.")
    self.failure_reason = "glitch"
    self.set_goal(self.state)
    return(1, escape.gen_ss(self.next_seed, self.goal), np.copy(self.goal))
```

**Comment by mattlangford** [comment]
There I was minding my own business driving around and all of a sudden this happened to me!

``` bash
Preparing: drive 
Rotating towards goal (duration: 1.36)
OpenCV Error: Bad flag (parameter or structure field) (Unrecognized or unsupported array type) in cvGetMat, file /home/matt/Downloads/opencv-2.4.9/modules/core/src/array.cpp, line 2482

A sample space image during select_exploration may have become degenerate. How odd.
type(ss_img): <type 'numpy.ndarray'>
np.shape(ss_img): (601, 0)
current push: [80, 40, 0, 0]
ss_goal: (120, 40)

Terminating.
```

`np.shape(ss_img): (601, 0)` << Could this be an issue?

I set the waypoint towards the bottom left corner of this grid. It had started rotating then after a second or two it gave the error and terminated the move.
![image](https://cloud.githubusercontent.com/assets/10998371/19780911/0ce79af6-9c55-11e6-9e94-ecf40cae62c2.png)

**Comment by mattlangford** [comment]
Also, in `boundary_analysis` I'm encountering the same issue (with it's floodFill)

**Comment by jnez71** [comment]
Yes, as suspected the problem is that somehow ss_img is getting one dimension of length zero. Based on the 0's in push's y-components, I think I know exactly why this is happening. Will fix soon.

**Comment by jnez71** [comment]
The current fix just picks some basic sample space (unadvised by the ogrid geometry, like the old days) when we get into the special (and rare) degenerate case. I haven't been able to recreate the degenerate case since implementing this fix, so it may not work as intended, and thus this issue will not close yet. Please report here if the print statement tells you to.

**Comment by jnez71** [comment]
It seems that there are multiple causes of the degenerate case. One we know for sure is being too close to the edge of the ogrid. Regardless, the resulting failure is the same in every case, so we have protected against it by catching the degenerate ss_img and reverting to the old style ogrid analysis as needed.
